actualites_index:
    path:     /
    defaults: { _controller: "LucieDesaintBundle:Actualites:index" }
    methods:  GET

actualites_show:
    path:     /{id}/show
    defaults: { _controller: "LucieDesaintBundle:Actualites:show" }
    methods:  GET

actualites_new:
    path:     /new
    defaults: { _controller: "LucieDesaintBundle:Actualites:new" }
    methods:  [GET, POST]

actualites_edit:
    path:     /{id}/edit
    defaults: { _controller: "LucieDesaintBundle:Actualites:edit" }
    methods:  [GET, POST]

actualites_delete:
    path:     /{id}/delete
    defaults: { _controller: "LucieDesaintBundle:Actualites:delete" }
    methods:  DELETE
