artiste_index:
    path:     /
    defaults: { _controller: "LucieDesaintBundle:Artiste:index" }
    methods:  GET

artiste_show:
    path:     /{id}/show
    defaults: { _controller: "LucieDesaintBundle:Artiste:show" }
    methods:  GET

artiste_new:
    path:     /new
    defaults: { _controller: "LucieDesaintBundle:Artiste:new" }
    methods:  [GET, POST]

artiste_edit:
    path:     /{id}/edit
    defaults: { _controller: "LucieDesaintBundle:Artiste:edit" }
    methods:  [GET, POST]

artiste_delete:
    path:     /{id}/delete
    defaults: { _controller: "LucieDesaintBundle:Artiste:delete" }
    methods:  DELETE
