categories_index:
    path:     /
    defaults: { _controller: "LucieDesaintBundle:Categories:index" }
    methods:  GET

categories_show:
    path:     /{id}/show
    defaults: { _controller: "LucieDesaintBundle:Categories:show" }
    methods:  GET

categories_new:
    path:     /new
    defaults: { _controller: "LucieDesaintBundle:Categories:new" }
    methods:  [GET, POST]

categories_edit:
    path:     /{id}/edit
    defaults: { _controller: "LucieDesaintBundle:Categories:edit" }
    methods:  [GET, POST]

categories_delete:
    path:     /{id}/delete
    defaults: { _controller: "LucieDesaintBundle:Categories:delete" }
    methods:  DELETE
