images_index:
    path:     /
    defaults: { _controller: "LucieDesaintBundle:Images:index" }
    methods:  GET

images_show:
    path:     /{id}/show
    defaults: { _controller: "LucieDesaintBundle:Images:show" }
    methods:  GET

images_new:
    path:     /new
    defaults: { _controller: "LucieDesaintBundle:Images:new" }
    methods:  [GET, POST]

images_edit:
    path:     /{id}/edit
    defaults: { _controller: "LucieDesaintBundle:Images:edit" }
    methods:  [GET, POST]

images_delete:
    path:     /{id}/delete
    defaults: { _controller: "LucieDesaintBundle:Images:delete" }
    methods:  DELETE
