produit_index:
    path:     /
    defaults: { _controller: "LucieDesaintBundle:Produit:index" }
    methods:  GET

produit_show:
    path:     /{id}/show
    defaults: { _controller: "LucieDesaintBundle:Produit:show" }
    methods:  GET

produit_new:
    path:     /new
    defaults: { _controller: "LucieDesaintBundle:Produit:new" }
    methods:  [GET, POST]

produit_edit:
    path:     /{id}/edit
    defaults: { _controller: "LucieDesaintBundle:Produit:edit" }
    methods:  [GET, POST]

produit_delete:
    path:     /{id}/delete
    defaults: { _controller: "LucieDesaintBundle:Produit:delete" }
    methods:  [GET, POST]
