<?php

namespace LucieDesaintBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCateg($categ){
        return $qb = $this->createQueryBuilder('p')
            ->select('i.src AS image')
            ->join('p.categorie', 'c')
            ->where('c.label_fr = :categ')
            ->join('p.image', 'i')
            ->setParameter('categ', $categ)
            ->getQuery()
            ->getResult();
    }
}