LucieDesaintBundle\Entity\Actualites:
    type: entity
    table: null
    repositoryClass: LucieDesaintBundle\Repository\ActualitesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
    lifecycleCallbacks: {  }
