LucieDesaintBundle\Entity\Artiste:
    type: entity
    table: null
    repositoryClass: LucieDesaintBundle\Repository\ArtisteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        textepresentation:
            type: text
        textback:
            type: string
            length: 255
        textback2:
            type: string
            length: 255
    lifecycleCallbacks: {  }
