LucieDesaintBundle\Entity\Categories:
    type: entity
    table: null
    repositoryClass: LucieDesaintBundle\Repository\CategoriesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        label_fr:
            type: string
            length: 255
        label_en:
            type: string
            length: 255

    lifecycleCallbacks: {  }
