LucieDesaintBundle\Entity\Produit:
    type: entity
    table: null
    repositoryClass: LucieDesaintBundle\Repository\ProduitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        info:
            type: string
            length: 255
            nullable: true
        prix:
            type: string
            length: 255
            nullable: true

    manyToOne:
        categorie:
            targetEntity: Categories
        image:
            targetEntity: Images
            cascade: ["persist", "remove"]

    lifecycleCallbacks: {  }
