LucieDesaintBundle\Entity\Produit:
    type: entity
    table: null
    repositoryClass: LucieDesaintBundle\Repository\ProduitRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
        info:
            type: string
            length: 255
            nullable: true
        Prix:
            type: string
            length: 255
            nullable: true
        Image:
            type: string
            length: 255
            nullable: true
        Alt:
            type: string
            length: 255
            nullable: true

    manyToOne:
        categories:
            targetEntity: Categories

    lifecycleCallbacks: {  }
