lucie_desaint_images:
    resource: "@LucieDesaintBundle/Resources/config/routing/images.yml"
    prefix:   /images

lucie_desaint_homepage:
    path:     /
    defaults: { _controller: LucieDesaintBundle:Default:index }

lucie_desaint_art:
    path:     /art
    defaults: { _controller: LucieDesaintBundle:Default:art }

lucie_desaint_bijoux:
        path:     /bijoux
        defaults: { _controller: LucieDesaintBundle:Default:bijoux }

lucie_desaint_contact:
        path:     /contact
        defaults: { _controller: LucieDesaintBundle:Default:contact }

lucie_desaint_artistes:
        path:     /artiste
        defaults: { _controller: LucieDesaintBundle:Default:artiste }

lucie_desaint_artiste:
    resource: "@LucieDesaintBundle/Resources/config/routing/artiste.yml"
    prefix:   /artiste

lucie_desaint_produit:
    resource: "@LucieDesaintBundle/Resources/config/routing/produit.yml"
    prefix:   /produit

lucie_desaint_categories:
    resource: "@LucieDesaintBundle/Resources/config/routing/categories.yml"
    prefix:   /categories

lucie_desaint_actualites:
    resource: "@LucieDesaintBundle/Resources/config/routing/actualites.yml"
    prefix:   /actualites



